### ISSUE TITLE
Add ability to set prefix

### ISSUE THREAD

**Issue by hthuong09** [kbrgl/scroller#2]
While working it with my bar. I can't figure out a way to put a static character that would not move to FIFO file. Then I tried change source code a bit and make it like this
![screenshot at 2016-06-17 20 21 55](https://cloud.githubusercontent.com/assets/8191266/16151860/3c2bd866-34c9-11e6-9bc2-89b20d4c2122.png)
I think that would be great if you can add this to official repo.

Thanks ;D

**Comment by kbrgl** [comment]
Can you send me a PR for this? It seems you've already written the code.

**Comment by kbrgl** [comment]
Hey there, hthuong09!

I just wanted to let you know that I've re-implemented Scroller in Rust (and renamed it to Roller). The prefix / postfix feature has been added in to the implementation.

**Comment by kbrgl** [comment]
This feature has been implemented as of [commit a0d94ab](https://github.com/kbrgl/scroller/commit/a0d94abc7438f3bc1880a8dee9a767adb9be5228)
